os: osx
osx_image: xcode9

before_install:
    - brew tap vapor/tap
    - brew update
    - brew install ctls mysql
    - mysql.server start
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;' -uroot

script:
    - swift build
    - swift build -c release
    - swift package generate-xcodeproj
    - xcodebuild -scheme Vapor-Package -enableCodeCoverage YES test | xcpretty

after_success:
    - eval "$(curl -sL https://swift.vapor.sh/codecov)"