#language: objective-c

#before_install:
#- brew update
#- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

#script:
#- touch /Users/travis/build/tannernelson/vapor/Sources/main.swift
#- xctool clean build -project Vapor.xcodeproj -scheme Vapor
#- xctool test -project Vapor.xcodeproj -scheme Tests

os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash
script:
  - . ~/.swiftenv/init
  - git clone https://github.com/apple/swift-package-manager swiftpm
  - cd swiftpm && git checkout 0373b84 && cd ../
  - swiftpm/Utilities/bootstrap
  - ${PWD}/swiftpm/.build/debug/swift-build
  - ${PWD}/swiftpm/.build/debug/swift-test
