version: 2

jobs:
  linux:
    docker:
      - image: swift:5.0
    steps:
      - checkout
      - run: apt-get update; apt-get install libssl-dev
      - run: swift build
      - run: swift test
  linux-release:
    docker:
      - image: swift:5.0
    steps:
      - checkout
      - run: apt-get update; apt-get install libssl-dev
      - run: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release
