name: deploy-api-docs
on: pull_request
# on:
#   push:
#     branches:
#       - master

jobs:
  deploy:
    name: api.vapor.codes
    runs-on: ubuntu-latest
    steps:
    - name: Deploy api-docs
      uses: appleboy/ssh-action@master
      with:
        host: api.vapor.codes
        username: vapor
        key: ${{ secrets.VAPOR_CODES_SSH_KEY }}
        script: |
          ./github-actions/deploy-api-docs.sh
