name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  bionic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test
      run: docker run -v $(pwd):/app vapor/swift:5.1-bionic swift test --package-path /app 
  bionic-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build release
      run: docker run -v $(pwd):/app vapor/swift:5.1-bionic swift build --package-path /app -c release
  bionic-thread:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test thread sanitizer
      run: docker run -v $(pwd):/app vapor/swift:5.1-bionic swift test --package-path /app --sanitize=thread
  xenial:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test
      run: docker run -v $(pwd):/app vapor/swift:5.1-xenial swift test --package-path /app 
  xenial-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build release
      run: docker run -v $(pwd):/app vapor/swift:5.1-xenial swift build --package-path /app -c release
  # macos:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: test
  #     run: swift test
  # macos-release:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: build release
  #     run: swift build -c release
